name: puppeteer-sharp-extra pipeline
run-name: "build and package puppeteer-sharp-extra"
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        cache: true
        source-url: https://nuget.pkg.github.com/krandor/index.json
      env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}
    - name: Restore dependencies
      run: dotnet restore **/*.sln
    - name: Build
      run: dotnet build --no-restore **/*.sln

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          cache: true
          source-url: https://nuget.pkg.github.com/krandor/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}
      - run: dotnet build --configuration Release **/*.sln
      - name: Create the package
        run: dotnet pack --configuration Release **/*.sln
      - name: Publish the package to GPR
        run: dotnet nuget push **/bin/Release/*.nupkg